### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by DSAghicha** [kumaraditya303/Library-Management-System#33]
The script is raising an **Internal Server Error**.

Probably on _SQLAlchemy_
![image](https://user-images.githubusercontent.com/53931676/109063662-710fae80-770f-11eb-80df-0b3d03827257.png)

**Comment by kumaraditya303** [comment]
@DSAghicha It is fixed now.

**Comment by DSAghicha** [comment]
Thanks!
